<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.51.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.50.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.24.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7" />

    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.4.0" />

    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.17.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Aep.Cmo.Shared.AppConfiguration\Aep.Cmo.Shared.AppConfiguration.csproj" />
    <ProjectReference Include="..\..\Shared\Aep.Cmo.Shared.Domain\Aep.Cmo.Shared.Domain.csproj" />
    <ProjectReference Include="..\..\Shared\Aep.Cmo.Shared.KeyVault\Aep.Cmo.Shared.KeyVault.csproj" />
    <ProjectReference Include="..\Aep.Cmo.Event.Orchestrator.Application\Aep.Cmo.Event.Orchestrator.Application.csproj" />
  </ItemGroup>

</Project>
